version: "3.9"  # optional since v1.27.0
volumes:
    postgres_13_data: {}
services:
    db:
        image: postgres:13-alpine
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_13_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: forza_challenge_demo_dev

